name: Deploy Portfolio to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/abi-saad-raphael/htdocs/raphael.abi-saad.fr

            git config --global --add safe.directory /home/abi-saad-raphael/htdocs/raphael.abi-saad.fr

            git reset --hard
            git pull origin main

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH="$HOME/.yarn/bin:$PATH"

            yarn install
            yarn build

            if pm2 list | grep -q raphael-portfolio; then
              pm2 reload raphael-portfolio
            else
              pm2 start yarn --name "raphael-portfolio" -- start
            fi

            pm2 save
